'use client';

import { Suspense } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { useState } from 'react';

const formSchema = z.object({
  code: z
    .string()
    .min(6, { message: 'O código deve ter 6 dígitos.' })
    .max(6, { message: 'O código deve ter 6 dígitos.' }),
});

function VerifyPageContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const email = searchParams.get('email');
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);

  // Fallback if email is not in query params
  if (!email) {
    return (
        <div className="flex items-center justify-center min-h-screen bg-gray-100">
            <Card className="w-full max-w-sm text-center">
                 <CardHeader>
                    <CardTitle className="text-2xl">Erro</CardTitle>
                    <CardDescription>
                        Não foi possível encontrar o e-mail para verificação.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Link href="/register">
                        <Button variant="outline">Voltar ao Registro</Button>
                    </Link>
                </CardContent>
            </Card>
        </div>
    );
  }

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      code: '',
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    // SIMULATION: In a real app, you would call a server action
    // to verify the code against a database. Here, we just check a static value.
    // The actual code is generated by Genkit and logged to the server console,
    // but we can't access it here. We'll use a placeholder for now.
    // To make this testable, you would need to check the server logs for the real code.
    console.log(`Verifying code for ${email}...`);

    // Simulate a network delay
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    // This is a simplified check. A real app would have a proper verification flow.
    // We assume any 6-digit code is potentially valid for the simulation.
    if (values.code.length === 6) {
      toast({
        title: 'Conta Verificada!',
        description: 'Sua conta foi verificada com sucesso. Agora você pode fazer o login.',
      });
      router.push('/login');
    } else {
      toast({
        title: 'Código Inválido',
        description: 'O código de verificação está incorreto. Tente novamente.',
        variant: 'destructive',
      });
      setIsLoading(false);
    }
  }

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle className="text-2xl">Verifique sua Conta</CardTitle>
          <CardDescription>
            Enviamos um código de 6 dígitos para {email}. Insira-o abaixo.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-4">
              <FormField
                control={form.control}
                name="code"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Código de Verificação</FormLabel>
                    <FormControl>
                      <Input placeholder="123456" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? 'Verificando...' : 'Verificar'}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}


export default function VerifyPage() {
    return (
        <Suspense fallback={<div>Carregando...</div>}>
            <VerifyPageContent />
        </Suspense>
    )
}
